package com.zzj.open.module_chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzj.open.module_chat.bean.ChatMessageModel;

import com.zzj.open.module_chat.db.ChatMessageModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageModelDaoConfig;

    private final ChatMessageModelDao chatMessageModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageModelDaoConfig = daoConfigMap.get(ChatMessageModelDao.class).clone();
        chatMessageModelDaoConfig.initIdentityScope(type);

        chatMessageModelDao = new ChatMessageModelDao(chatMessageModelDaoConfig, this);

        registerDao(ChatMessageModel.class, chatMessageModelDao);
    }
    
    public void clear() {
        chatMessageModelDaoConfig.clearIdentityScope();
    }

    public ChatMessageModelDao getChatMessageModelDao() {
        return chatMessageModelDao;
    }

}
