package com.zzj.open.module_chat.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzj.open.module_chat.bean.ChatListModel;
import com.zzj.open.module_chat.bean.ChatMessageModel;
import com.zzj.open.module_chat.bean.GroupCard;
import com.zzj.open.module_chat.bean.MyFriendModel;

import com.zzj.open.module_chat.db.ChatListModelDao;
import com.zzj.open.module_chat.db.ChatMessageModelDao;
import com.zzj.open.module_chat.db.GroupCardDao;
import com.zzj.open.module_chat.db.MyFriendModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatListModelDaoConfig;
    private final DaoConfig chatMessageModelDaoConfig;
    private final DaoConfig groupCardDaoConfig;
    private final DaoConfig myFriendModelDaoConfig;

    private final ChatListModelDao chatListModelDao;
    private final ChatMessageModelDao chatMessageModelDao;
    private final GroupCardDao groupCardDao;
    private final MyFriendModelDao myFriendModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatListModelDaoConfig = daoConfigMap.get(ChatListModelDao.class).clone();
        chatListModelDaoConfig.initIdentityScope(type);

        chatMessageModelDaoConfig = daoConfigMap.get(ChatMessageModelDao.class).clone();
        chatMessageModelDaoConfig.initIdentityScope(type);

        groupCardDaoConfig = daoConfigMap.get(GroupCardDao.class).clone();
        groupCardDaoConfig.initIdentityScope(type);

        myFriendModelDaoConfig = daoConfigMap.get(MyFriendModelDao.class).clone();
        myFriendModelDaoConfig.initIdentityScope(type);

        chatListModelDao = new ChatListModelDao(chatListModelDaoConfig, this);
        chatMessageModelDao = new ChatMessageModelDao(chatMessageModelDaoConfig, this);
        groupCardDao = new GroupCardDao(groupCardDaoConfig, this);
        myFriendModelDao = new MyFriendModelDao(myFriendModelDaoConfig, this);

        registerDao(ChatListModel.class, chatListModelDao);
        registerDao(ChatMessageModel.class, chatMessageModelDao);
        registerDao(GroupCard.class, groupCardDao);
        registerDao(MyFriendModel.class, myFriendModelDao);
    }
    
    public void clear() {
        chatListModelDaoConfig.clearIdentityScope();
        chatMessageModelDaoConfig.clearIdentityScope();
        groupCardDaoConfig.clearIdentityScope();
        myFriendModelDaoConfig.clearIdentityScope();
    }

    public ChatListModelDao getChatListModelDao() {
        return chatListModelDao;
    }

    public ChatMessageModelDao getChatMessageModelDao() {
        return chatMessageModelDao;
    }

    public GroupCardDao getGroupCardDao() {
        return groupCardDao;
    }

    public MyFriendModelDao getMyFriendModelDao() {
        return myFriendModelDao;
    }

}
